[build]
# 位置独立コード(position-independent code; PIC)とは、相対的な位置を保っているならば、
# 命令列をどのメモリ上のアドレスに置いても良いコード(命令列)のことである。
# Rustのコンパイラは、RustのコードからOSとCPUが解釈可能な実行可能バイナリファイルを出力する。
# このとき、出力されたコードを、メモリ上のどのアドレスへも配置して良い場合、それは位置独立コードと呼ばれ、
# 位置独立コードからのみなる実行ファイルは位置独立実行形式(position-inependent executable; PIE)であるという。
# Rustコンパイラはデフォルトでは位置独立実行形式の実行ファイルを出力する。
# 実行ファイル中では0x8000の位置にある命令は、理論的にはメモリ上のどのアドレスに配置しても良い(他の命令との相対的な位置は保持する必要がある)
# ASLRは実行ファイルが位置独立コードであるからこそ実現できる。
#
# -Crelocation-model=dynamic-no-picはRustコンパイラに位置独立実行形式の実行ファイルを生成しないと指定するオプション
# テスト時には位置独立実行形式でないほうがわかりやすいため、このように設定する
rustflags = ["-Crelocation-model=dynamic-no-pic"]