name: Bench

on:
  pull_request:

jobs:
  bench:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2 
      - uses: boa-dev/criterion-compare-action@v3
        with:
          benchName: "benchmark"
          # Needed. The name of the branch to compare with. This default uses the branch which is being pulled against
          branchName: ${{ github.base_ref }}